version: "3.8"

services:
    app:
        image: php:8.2-fpm
        container_name: sistem_penggajian_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - sistempenggajian

    webserver:
        image: nginx:alpine
        container_name: sistem_penggajian_webserver
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - sistempenggajian
        depends_on:
            - app

    db:
        platform: linux/x86_64
        image: mysql:5.7
        container_name: sistem_penggajian_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - sistempenggajian

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - "8081:80"
        depends_on:
            - db
        networks:
            - sistempenggajian

networks:
    sistempenggajian:

volumes:
    dbdata:
